variables:
  RUN_RENOVATE:
    value: "no"
    options:
      - "yes"
      - "no"
    description: "Set to yes to run Renovate instead of the pipeline"

include:
  - component: $CI_SERVER_FQDN/univention/dev/tooling/ci-components/renovate@2.19.0
    rules:
      - if: $RUN_RENOVATE == "yes"

debian-bookworm:
  image: debian:bookworm
  rules:
    - if: $RUN_RENOVATE != "yes"
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends
        ca-certificates curl devscripts dpkg-dev equivs git lintian
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
  script:
    - mkdir build
    - debian/build-source-package build
    - cd build
    - dpkg-source -x toolong_*.dsc src
    - cd src
    - mk-build-deps -i -r -t "apt-get -y -qq --no-install-recommends" debian/control
    - dpkg-buildpackage -us -uc
    - cd ..
    - lintian --fail-on error *.changes
    - apt-get install -y -qq ./toolong_*_all.deb
    - tl --version
  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.*
